{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "erpc.fullname" . }}
  labels:
    {{- include "erpc.labels" . | nindent 4 }}
  {{- with .Values.monitoring.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.monitoring.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "erpc.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      {{- with .Values.monitoring.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.path }}
      path: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.monitoring.podMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.monitoring.podMonitor.jobLabel }}
  jobLabel: {{ . }}
  {{- end }}
  {{- with .Values.monitoring.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.monitoring.podMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .Values.monitoring.podMonitor.targetLimit }}
  targetLimit: {{ . }}
  {{- end }}
{{- end }}