{{- if (index .Values "erpc-haproxy-hpa" "enabled") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: erpc-erpc-haproxy
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/instance: erpc-erpc-haproxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erpc-erpc-haproxy
  minReplicas: {{ index .Values "erpc-haproxy-hpa" "minReplicas" }}
  maxReplicas: {{ index .Values "erpc-haproxy-hpa" "maxReplicas" }}
  metrics:
    {{- if index .Values "erpc-haproxy-hpa" "targetCPUUtilizationPercentage" }}
    - type: Pods
      pods:
        metric:
          name: cpu_utilization_percentage
        target:
          type: AverageValue
          averageValue: {{ index .Values "erpc-haproxy-hpa" "targetCPUUtilizationPercentage" }}
    {{- end }}
    {{- if index .Values "erpc-haproxy-hpa" "targetMemoryUtilizationPercentage" }}
    - type: Pods
      pods:
        metric:
          name: memory_utilization_percentage
        target:
          type: AverageValue
          averageValue: {{ index .Values "erpc-haproxy-hpa" "targetMemoryUtilizationPercentage" }}
    {{- end }}
{{- end }}
