apiVersion: v1
kind: ServiceAccount
metadata:
  name: erpc
  labels:
    app.kubernetes.io/name: erpc-vault
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    {{- with .Values.erpc.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
