name: Helm Chart Validation

on:
  push:
    branches: [morpho-main]
    paths:
      - 'helm/**'
      - '.github/workflows/helm-charts-validation.yaml'
  pull_request:
    branches: [morpho-main]
    paths:
      - 'helm/**'
      - '.github/workflows/helm-charts-validation.yaml'

jobs:
  helm-charts-validation:
    uses: morpho-org/github-actions/.github/workflows/helm-charts-validation.yml@v1
    with:
      runner: ubuntu-latest
      skip-patterns: "*-db,*database*,*postgres*"
