name: Wiz IaC Scan

on:
  pull_request:
    paths:
      - 'helm/**'
      - '.github/workflows/wiz-iac-scan.yml'

permissions:
  contents: read

jobs:
  wiz-iac-scan:
    uses: morpho-org/github-actions/.github/workflows/wiz-iac-scan.yml@v1
    with:
      scan-path: "helm/"
    secrets:
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
